--liquibase format sql
--changeset matheuscosantos:1

CREATE SEQUENCE IF NOT EXISTS hibernate_sequence;

CREATE TABLE IF NOT EXISTS usuario (
					  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY CONSTRAINT usuario_pkey PRIMARY KEY, 
					  email VARCHAR(255) NOT NULL, 
					  nome VARCHAR(255) NOT NULL, 
					  senha VARCHAR(255) NOT NULL 								  	  
				   );
								   
--rollback DROP TABLE IF EXISTS usuario CASCADE;
								   
CREATE TABLE IF NOT EXISTS lancamento (
					 id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY CONSTRAINT lancamento_pkey PRIMARY KEY, 
					 titulo VARCHAR(255) NOT NULL,
					 descricao VARCHAR(255),						 
					 dia integer NOT NULL, 
					 mes integer NOT NULL, 
					 ano integer NOT NULL,
					 tipo VARCHAR(15) NOT NULL,					 
					 valor decimal(19,2) NOT NULL, 
					 usuario_id BIGINT CONSTRAINT usuario_fkey REFERENCES usuario
					 );	
										 
--rollback DROP TABLE IF EXISTS lancamento CASCADE;      
--rollback DROP SEQUENCE hibernate_sequence;

--changeset teste:2								   
CREATE TABLE IF NOT EXISTS perfil (
					 id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY CONSTRAINT perfil_pkey PRIMARY KEY, 
			         nomes VARCHAR(255)
			        );

--rollback DROP TABLE IF EXISTS perfil CASCADE;			
 
CREATE TABLE IF NOT EXISTS usuario_perfis (
					 usuario_id BIGINT CONSTRAINT usuario_fkey REFERENCES usuario, 
			    	 perfis_id BIGINT CONSTRAINT perfil_fkey REFERENCES perfil
			       );					       

--rollback DROP TABLE IF EXISTS usuario_perfis CASCADE;				    						    	 
					    	 
--changeset matheuscosantos:3	
ALTER TABLE perfil RENAME COLUMN nomes TO nome;
--rollback ALTER TABLE perfil RENAME nome TO nomes;
  	 
					    	 
					    	 