--liquibase formatted sql

--changeset matheuscosantos:1

create table lancamento (id bigint generated by default as identity, 
						 ano integer not null, 
						 descricao varchar(255), 
						 dia integer not null, 
						 mes integer not null, 
						 tipo varchar(255), 
						 titulo varchar(255),
						 valor decimal(19,2), 
						 usuario_id bigint, 
						 primary key (id));

create table perfil (id bigint generated by default as identity, 
			         nome varchar(255), 
			         primary key (id))

create table usuario (id bigint generated by default as identity, 
					  email varchar(255), 
					  nome varchar(255), 
					  senha varchar(255), 
				      primary key (id));

create table usuario_perfis (usuario_id bigint not null, 
					    	 perfis_id bigint not null);
					    
					    	 
--rollback DROP TABLE perfil
--rollback DROP TABLE lancamento;
--rollback DROP TABLE product;

					    	 
					    	 
					    	 
					    	 
					    	 