project.name: controle_financeiro

spring:
  application:
  name: ${project.name}

  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:alura-forum
    username: sa
    password:
    initialize: true

  jpa:
    show-sql: true
    hibernate: 
    ddl-auto: update
    
    properties.hibernate: 
      show_sql: true
      formate_sql: true
      naming-strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy
      ddl-auto: validate
      database-platform: org.hibernate.dialect.H2Dialect

    h2.console:
     enabled: true
     path: /h2-console

forum:
  jwt: 
    secret: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
    expiration: 864000000
