project.name: controle_financeiro

spring:
  application:
  name: ${project.name}

  datasource:
    url: jdbc:postgresql://localhost/bdcontrolefinanceiro
    username: postgres
    password: 123
    initialize: true
    initialization-mode: always

  jpa:
    database: postgresql
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate: 
      ddl-auto: update
      enabled: true
    
    properties.hibernate: 
      show_sql: true
      formate_sql: true
      naming-strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy
      ddl-auto: validate
      

forum:
  jwt: 
    secret: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
    expiration: 864000000
